from docx.shared import RGBColor


ANEXO_FONT_SIZE = 10
ANEXO_IV_FONT_SIZE = 10

ANEXO_III_HEADER_FILL = "4F81BD"
ANEXO_IV_TABLE_HEADER_FILL = "D9D9D9"
WHITE_FILL = "FFFFFF"
LIGHT_BORDER = "BFBFBF"
SUGGESTION_COLOR = RGBColor(192, 0, 0)

ANEXO_III_HEADER_ROW_HEIGHT_CM = 1.7
ANEXO_III_TABLE_WIDTH_PERCENT = 97
ANEXO_III_HOURS_COLUMN_WIDTH_CM = 2.2
ANEXO_III_DATES_COLUMN_WIDTH_CM = 5.5

ANEXO_IV_UF_ROW_MIN_HEIGHT_CM = 1.4
ANEXO_IV_MAIN_HEADER_ROW_HEIGHT_CM = 2.6
ANEXO_IV_TABLE_WIDTH_PERCENT = 100

DOC_HEADER_TOP_MARGIN_INCHES = 1.3
DOC_HEADER_TABLE_WIDTH_INCHES = 9.5
DOC_HEADER_LOGO_WIDTH_INCHES = 2.2
DOC_HEADER_SPACE_AFTER_PT = 20
DOC_HEADER_TEACHER_FONT_SIZE = 10
